version: '3'
services:

  prom:
    image: "zrbcool/prometheus-lua-prom:v1.0"
    ports:
     - "9090:9090"

  grafana:
    image: "zrbcool/prometheus-lua-grafana:v1.0"
    ports:
     - "3000:3000"

  resty:
    image: "zrbcool/prometheus-lua-nginx:v1.0" 
    ports:
     - "80:80"
     - "9145:9145"

  backend:
    image: "zrbcool/prometheus-lua-backend:latest"
    ports:
     - "8081:8081"
