apiVersion: 1

deleteDatasources:
   - name: Prometheus
     orgId: 1

datasources:
 - name: Prometheus-Aggregator 
   type: prometheus
   access: proxy
   orgId: 1
   url: http://prom:9090
   isDefault: true
   jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
   # <string> json object of data that will be encrypted.
   secureJsonData:
   version: 1
   editable: false

